{% set version = "2.0.1" %}

package:
  name: wrapt
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/wrapt/wrapt-{{ version }}.tar.gz
  sha256: 9c9c635e78497cacb81e84f8b11b23e0aacac7a136e73b8e5b2109a1d9fc468f

build:
  number: 1
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=38.3.0
    - pip
  run:
    - python

test:
  imports:
    - wrapt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GrahamDumpleton/wrapt
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Module for decorators, wrappers and monkey patching
  description: |
    The aim of the wrapt module is to provide a transparent object proxy for
    Python, which can be used as the basis for the construction of function
    wrappers and decorator functions.
  doc_url: http://wrapt.readthedocs.org/en/latest/
  doc_source_url: https://github.com/GrahamDumpleton/wrapt/blob/master/docs/index.rst
  dev_url: https://github.com/GrahamDumpleton/wrapt

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
    - ocefpaf
