schema_version: 1

context:
  version: 2.0.1

package:
  name: wrapt
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/w/wrapt/wrapt-${{ version }}.tar.gz
  sha256: 9c9c635e78497cacb81e84f8b11b23e0aacac7a136e73b8e5b2109a1d9fc468f

build:
  number: 2
  skip:
    - if: python_version < "3.7"
      then: true
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - setuptools >=38.3.0
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - wrapt
      pip_check: true

about:
  homepage: https://github.com/GrahamDumpleton/wrapt
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Module for decorators, wrappers and monkey patching
  description: |
    The aim of the wrapt module is to provide a transparent object proxy for
    Python, which can be used as the basis for the construction of function
    wrappers and decorator functions.
  documentation: http://wrapt.readthedocs.org/en/latest/
  repository: https://github.com/GrahamDumpleton/wrapt

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
    - ocefpaf
