schema_version: 1

context:
  version: "2.4.1"

package:
  name: wrapt
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/w/wrapt/wrapt-${{ version }}.tar.gz
  sha256: fd6390aab9e8aa40c52eff3c180f098e8d9f5894b1fd4c4fd2c207067b33ed16

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
  host:
    - python
    - setuptools >=62.0
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - wrapt
      pip_check: true

about:
  summary: Module for decorators, wrappers and monkey patching.
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://github.com/GrahamDumpleton/wrapt
  documentation: https://wrapt.readthedocs.io/

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
    - ocefpaf
